# Pandas

In [5]:
!pip install pandas

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in .\.venv\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
import pandas as pd
print(pd.__version__)

3.0.2

In [7]:
import sys
print(sys.executable)

c:\Users\DELL\OneDrive\Desktop\Python Datascience\.venv\Scripts\python.exe

In [8]:
import pandas as pd

# Data create
data = {
    "Name": ["Ram", "Shyam", "Hari"],
    "Age": [20, 22, 21],
    "Marks": [80, 75, 90]
}

# DataFrame
df = pd.DataFrame(data)

# Data print
print("Full Data:")
print(df)

# First 2 rows
print("\nFirst 2 rows:")
print(df.head(2))

# Mean (average)
print("\nAverage Marks:")
print(df["Marks"].mean())

# Max marks
print("\nHighest Marks:")
print(df["Marks"].max())

Full Data:
    Name  Age  Marks
0    Ram   20     80
1  Shyam   22     75
2   Hari   21     90

First 2 rows:
    Name  Age  Marks
0    Ram   20     80
1  Shyam   22     75

Average Marks:
81.66666666666667

Highest Marks:
90

In [9]:
import pandas as pd
data = ["apple", "ball", "cat"]
result = pd.Series(data)
print(result)

0    apple
1     ball
2      cat
dtype: str

In [10]:
data =  {"Name": ["Ram", "Shyam", "Hari"],
    "Age": [20, 22, 21],
    "Marks": [80, 75, 90]
    }
# dataframe
df = pd.DataFrame(data)
print(df)

    Name  Age  Marks
0    Ram   20     80
1  Shyam   22     75
2   Hari   21     90

In [11]:
data = {"Employees":["Balkrishna", "Gita","Nawaraj", "Raju","Anshu"],
        "designation": ["Manager","staff","Assistance","मिस्तिरी","बेपारी"],
        "salary": ["130000","50000","25000","1200","5000"]
        }
df = pd.DataFrame(data)
# print(df)
df.head()
# df.head(2)
# df["Employees"].max()

    Employees designation  salary
0  Balkrishna     Manager  130000
1        Gita       staff   50000
2     Nawaraj  Assistance   25000
3        Raju    मिस्तिरी    1200
4       Anshu      बेपारी    5000

In [12]:
df = pd.read_csv("customers-100.csv")
# print(df)
# df.head()
df.head(500)
# df["First Name"].max()
# df.loc()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,8/24/2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,4/23/2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,(496)978-3969x58947,beckycarr@hogan.com,3/25/2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,6/2/2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,4/17/2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,1/30/2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,7/10/2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,9/18/2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,8/11/2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,3/11/2020,http://www.hatfield-saunders.net/

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    str
 2   First Name         100 non-null    str
 3   Last Name          100 non-null    str
 4   Company            100 non-null    str
 5   City               100 non-null    str
 6   Country            100 non-null    str
 7   Phone 1            100 non-null    str
 8   Phone 2            100 non-null    str
 9   Email              100 non-null    str
 10  Subscription Date  100 non-null    str
 11  Website            100 non-null    str
dtypes: int64(1), str(11)
memory usage: 9.5 KB

In [14]:
df.describe()

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [15]:
df = pd.read_csv("Mobile_data.csv")
# print(df)
# df.head(100)
# df["brand_name"].max()
# df["brand_name"].unique()
# df.describe()
# df.columns
# df["Unnamed: 0"].drop()
df.drop(columns="Unnamed: 0", inplace=True)
# df.drop(columns="Unnamed: 0", inplace=False)
df.isnull().sum()

# df.head()
# df.columns
# df[["brand_name"] == "KAIoS"]
# df[["brand_name"] == "Vivo"]

brand_name          0
model_name          0
os                197
popularity          0
best_price          0
lowest_price      260
highest_price     260
sellers_amount      0
screen_size         2
memory_size       112
battery_size       10
release_date        0
dtype: int64

# Example Workdown

In [16]:
# df.isnull().sum()
# df.duplicated().sum()
df.drop_duplicates()
# df.groupby('brand_name')
# df['highest_price'] = df['highest_price']
# print("mean is ", x)data

,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529.0,1819.0,36,5.00,8.0,2000.0,20-Oct
1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,NaN,NaN,10,5.71,16.0,3000.0,20-Apr
...,...,...,...,...,...,...,...,...,...,...,...,...
1219,Apple,iPhone XS Max 64GB Gold (MT522),iOS,1101,22685,16018.0,27900.0,61,6.50,64.0,3174.0,18-Sep
1220,Apple,iPhone XS Max Dual Sim 64GB Gold (MT732),iOS,530,24600,21939.0,33720.0,28,6.50,64.0,3174.0,18-Sep
1221,HUAWEI,nova 5T 6/128GB Black (51094MEU),Android,1174,8804,7999.0,9999.0,18,6.26,128.0,3750.0,19-Nov
1222,ZTE,nubia Red Magic 5G 8/128GB Black,Android,752,18755,18500.0,19010.0,2,6.65,128.0,4500.0,20-Oct
1223,Sigma mobile,x-style 35 Screen,NaN,952,907,785.0,944.0,75,3.50,NaN,1750.0,20-Jan

In [17]:
# Series
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

0    1
1    7
2    2
dtype: int64

In [18]:
a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

x    1
y    7
z    2
dtype: int64

In [19]:

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64

In [20]:

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories, index = ["day1", "day2"])

print(myvar)

day1    420
day2    380
dtype: int64

In [21]:
# DataFrame
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

In [22]:
#refer to the row index:
print(df.loc[0])

calories    420
duration     50
Name: 0, dtype: int64

In [23]:
#use a list of indexes:
print(df.loc[[0, 1]])

   calories  duration
0       420        50
1       380        40

In [24]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45